MCP3008_MOSI = 10
MCP3008_MISO = 9
MCP3008_CLK = 11
MCP3008_CE0 = 8

DUMMY_ACTIVE = False
WATERLEVELSENSOR_ACTIVE = False
SOILSENSORS_ACTIVE = True
TEMPERATURESENSOR_ACTIVE = False

UART_TX = 14
UART_RX = 15

TESTING_LED_PIN = 17

SOILSENSOR_1_LABEL = "SoilSensor 1"
SOILSENSOR_2_LABEL = "SoilSensor 2"
SOILSENSOR_3_LABEL = "SoilSensor 3"
SOILSENSOR_4_LABEL = "SoilSensor 4"

SOILSENSOR_DISCONNECTED_TRESHOLD = 0.9
SOILSENSOR_UPPER_TRESHOLD = 0.6
SOILSENSOR_LOWER_TRESHOLD = 0.1

SOILSENSOR_READINGS = 10
SOILSENSOR_TIME_BETWEEN_READINGS = 0.01
